/**
 * @license
 * Copyright 2026 Google Inc.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Archives are generated by testdata/kvstore/vzip/generate_vzip.py.

import "#src/kvstore/http/register_frontend.js";
import "#src/kvstore/vzip/register_frontend.js";
import { describe, expect, test } from "vitest";
import { parsePipelineUrlComponent } from "#src/kvstore/url.js";
import { expandVzipSchemeUrl } from "#src/kvstore/vzip/scheme.js";
import { constantFixture } from "#tests/fixtures/fixture.js";
import { httpServerFixture } from "#tests/fixtures/http_server.js";
import { getTestFiles, TEST_DATA_DIR } from "#tests/kvstore/test_data.js";
import {
  readAllFromKvStore,
  sharedKvStoreContext,
  testAutoDetect,
  testKvStore,
} from "#tests/kvstore/test_util.js";

const serverFixture = httpServerFixture(constantFixture(TEST_DATA_DIR));

async function url(archive: string, key = "") {
  return (await serverFixture.serverUrl()) + `vzip/${archive}|vzip:${key}`;
}

async function read(archive: string, key: string) {
  const { kvStoreContext } = await sharedKvStoreContext();
  const response = await kvStoreContext.read(await url(archive, key), {
    throwIfMissing: true,
  });
  return new TextDecoder().decode(await response.response.arrayBuffer());
}

for (const archive of ["files.vzip", "files_paged.vzip"]) {
  describe(archive, () => {
    describe("kvstore operations", () => {
      testKvStore(() => url(archive));
    });

    test("every key matches the original file", async () => {
      const { kvStoreContext } = await sharedKvStoreContext();
      const kvStore = kvStoreContext.getKvStore(await url(archive));
      expect(await readAllFromKvStore(kvStore.store, kvStore.path)).toEqual(
        await getTestFiles(),
      );
    });

    test("hidden entries are not visible", async () => {
      const { kvStoreContext } = await sharedKvStoreContext();
      expect(
        await kvStoreContext.read(await url(archive, "__vz__/sources")),
      ).toBe(undefined);
      expect(
        (
          await kvStoreContext.list(await url(archive, "__vz__/"), {
            responseKeys: "suffix",
          })
        ).entries,
      ).toEqual([]);
    });
  });
}

test("auto-detect", async () => {
  const matches = await testAutoDetect(
    (await serverFixture.serverUrl()) + "vzip/files.vzip",
  );
  expect(matches.map((m) => m.suffix)).toContain("vzip:");
});

describe("pins over HTTP", () => {
  test("size and modified_not_after that hold", async () => {
    const b = (await getTestFiles()).get("b")!.toString();
    expect(await read("pins.vzip", "size_ok")).toEqual(b);
    expect(await read("pins.vzip", "mtime_ok")).toEqual(b);
  });
  test.for([
    ["size_wrong", /resolution error.*size pin/],
    ["mtime_too_early", /resolution error/],
    ["etag_wrong", /resolution error/],
  ] as const)("%s fails closed", async ([key, error]) => {
    await expect(read("pins.vzip", key)).rejects.toThrow(error);
  });
});

describe("errors", () => {
  test("bytes entry", async () => {
    expect(await read("errors.vzip", "ok")).toEqual("fine");
  });
  test.for([
    ["entry_error", /vzip entry error/],
    ["payload_error", /vzip payload error/],
    ["missing_url", /vzip resolution error/],
    ["missing_key", /vzip resolution error.*missing/],
    ["past_end", /vzip resolution error/],
  ] as const)("%s", async ([key, error]) => {
    await expect(read("errors.vzip", key)).rejects.toThrow(error);
  });

  test("ranges outside the window are not resolved", async () => {
    const { kvStoreContext } = await sharedKvStoreContext();
    const response = await kvStoreContext.read(
      await url("errors.vzip", "partial"),
      { byteRange: { offset: 0, length: 2 }, throwIfMissing: true },
    );
    expect(response.totalSize).toEqual(6);
    expect(await response.response.text()).toEqual("hi");
    await expect(read("errors.vzip", "partial")).rejects.toThrow(
      /vzip resolution error/,
    );
  });

  test("unsupported format version", async () => {
    await expect(read("future_version.vzip", "a")).rejects.toThrow(
      /vzip archive error: unsupported vzip format version "9"/,
    );
  });
});

describe("vzip:// scheme", () => {
  test("is shorthand for <archive-url>|vzip:", async () => {
    const archive = (await serverFixture.serverUrl()) + "vzip/files.vzip";
    const { kvStoreContext } = await sharedKvStoreContext();
    const viaScheme = kvStoreContext.getKvStore(`vzip://${archive}`);
    expect(viaScheme.store.getUrl(viaScheme.path)).toEqual(`${archive}|vzip:`);
    // The archive root itself is not a key.
    expect(await kvStoreContext.read(`vzip://${archive}`)).toBe(undefined);
  });

  test.for([
    ["https://h/d.vzip", "https://h/d.vzip|vzip:"],
    ["https://h/d.vzip/", "https://h/d.vzip|vzip:"],
    ["https://h/d.vzip/s0/zarr.json", "https://h/d.vzip|vzip:s0/zarr.json"],
    ["https://h/a.vzip/b.vzip/k", "https://h/a.vzip|vzip:b.vzip/k"],
    ["https://data.vzip.org/x.vzip/k", "https://data.vzip.org/x.vzip|vzip:k"],
    ["https://h/archive.zip", "https://h/archive.zip|vzip:"],
  ] as const)("vzip://%s", ([rest, expected]) => {
    expect(
      expandVzipSchemeUrl(parsePipelineUrlComponent(`vzip://${rest}`)),
    ).toEqual(expected);
  });

  describe("generic kvstore operations through vzip://", () => {
    testKvStore(
      async () => `vzip://${await serverFixture.serverUrl()}vzip/files.vzip/`,
    );
  });

  test("reads and lists through the scheme", async () => {
    const archive = (await serverFixture.serverUrl()) + "vzip/files_paged.vzip";
    const { kvStoreContext } = await sharedKvStoreContext();
    const kvStore = kvStoreContext.getKvStore(`vzip://${archive}`);
    expect(await readAllFromKvStore(kvStore.store, kvStore.path)).toEqual(
      await getTestFiles(),
    );
  });

  test.for([
    ["vzip://", /expected `vzip:\/\/<archive-url>`/],
    ["vzip:", /expected `vzip:\/\/<archive-url>`/],
    ["vzip://example.com/data.vzip", /the archive URL must have a scheme/],
  ] as const)("%s is rejected", async ([url, error]) => {
    const { kvStoreContext } = await sharedKvStoreContext();
    expect(() => kvStoreContext.getKvStore(url)).toThrow(error);
  });
});
